services:
  cobblerd:
    restart: always
    env_file:
      - .env
    container_name: 'cobblerd'
    hostname: ${SERVICEHOSTNAME}
    build:
      context: .
      dockerfile: 'centos9-cobblerd-springdale.Dockerfile'
    volumes:
      - './cobblerdata:/opt/import'
      # - './cobblerdata-work:/opt/import'
      - './cobblerimporter:/opt/cobblerimporter'
    ports:
      - "69:69/udp"
      - "69:69/tcp"
      - "25150:25150/udp"
      #- "${CLIENTPORT}:80"
    environment:
      - TZ=America/New_York
    networks:
      - default
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cobblerd-http.entrypoints=http"
      - "traefik.http.routers.cobblerd-https.entrypoints=https"
      - "traefik.http.routers.cobblerd-https.tls=true"
      - "traefik.http.routers.cobblerd-https.tls.certresolver=letsencrypt-resolver"
      #- "traefik.http.routers.cobblerd-http.middlewares=cobblerd-redirectscheme@docker"
      - "traefik.http.routers.cobblerd-http.rule=Host(`${SERVICEHOSTNAME}`)"
      - "traefik.http.routers.cobblerd-https.rule=Host(`${SERVICEHOSTNAME}`)"
      #- "traefik.http.middlewares.cobblerd-redirectscheme.redirectscheme.scheme=https"
      #- "traefik.http.middlewares.cobblerd-redirectscheme.redirectscheme.permanent=true"
      - "traefik.http.services.cobblerd.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true
