services:
  cobblerd:
    restart: always
    env_file:
      - .env
    container_name: 'cobblerd'
    hostname: ${SERVICEHOSTNAME}
    build:
      context: .
      dockerfile: 'centos9-cobblerd-springdale.Dockerfile'
    volumes:
      - './cobblerdata:/opt/import'
      # - './cobblerdata-work:/opt/import'
      - './cobblerimporter:/opt/cobblerimporter'
    ports:
      - "69:69/udp"
      - "25150:25150/udp"
      - "${CLIENTPORT}:80"
