version: '3'
services:
  cobblerd:
    env_file:
      - .env
    container_name: 'cobblerd'
    hostname: ${SERVICEHOSTNAME}
    build:
      context: .
      dockerfile: 'centos7-cobblerd.Dockerfile'
    ports:
      - "69:69/udp"
      - "25150:25150/udp"
      - "8888:8888"
    expose:
      - '80'
    networks:
      - default
      - proxy
    # labels:
      # - "traefik.enable=true"
      # - "traefik.http.routers.cobblerd-http.entrypoints=http"
      # - "traefik.http.routers.cobblerd-https.entrypoints=https"
      # - "traefik.http.routers.cobblerd-https.tls=true"
      # - "traefik.http.routers.cobblerd-https.tls.certresolver=letsencrypt-resolver"
      # - "traefik.http.routers.cobblerd-http.middlewares=cobblerd-redirectscheme@docker"
      # - "traefik.http.routers.cobblerd-http.rule=Host(`${SERVICEHOSTNAME}`)"
      # - "traefik.http.routers.cobblerd-https.rule=Host(`${SERVICEHOSTNAME}`)"
      # - "traefik.http.middlewares.cobblerd-redirectscheme.redirectscheme.scheme=https"
      # - "traefik.http.middlewares.cobblerd-redirectscheme.redirectscheme.permanent=true"
      # - "traefik.http.services.cobblerd.loadbalancer.server.port=80"
      # - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true
