version: '3'
services:
  cobblerd:
    env_file:
      - .env
    container_name: 'cobblerd'
    hostname: ${SERVICEHOSTNAME}
    build:
      context: .
      dockerfile: 'centos7-cobblerd.Dockerfile'
    volumes:
      #- './cobblerdata/varwww:/var/www/cobbler'
      #- './cobblerdata/varlib:/var/lib/cobbler'
      # - './cobblerdata:/opt/import'
      - './cobblerdata-work:/opt/import'
      - './cobblerimporter:/opt/cobblerimporter'
    ports:
      - "69:69/udp"
      - "25150:25150/udp"
      - "${CLIENTPORT}:${CLIENTPORT}"
    expose:
      - "${CLIENTPORT}"
    networks:
      - default
